[repository]
name = "example"
authors = ["name"]
commit_pins = [
    ["3bb9c7c5cf4f2ee30bf821501499f2308d616f94", "efee74a7404495dbda70205824d6e9fc923ccdae"],
]

[example]
description = "Example plugin description"
authors = ["name"]
output = "build/src/example.so"
build = [
    "meson setup build",
    "ninja -C build"
]
