[repository]
name = "hyprbalance"
authors = ["J-L1N"]
commit_pins = [
    ["3bb9c7c5cf4f2ee30bf821501499f2308d616f94", "efee74a7404495dbda70205824d6e9fc923ccdae"],
]

[example]
description = "Plugin that provides an additional dispatcher 'balance' to evenly divide window sizes"
authors = ["J-L1N"]
output = "build/src/hyprbalance.so"
build = [
    "meson setup build",
    "ninja -C build"
]
